include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_print: ignore
    invalid_annotation_target: ignore
    invalid_visibility_annotation: ignore
    prefer_const_constructors: ignore
    unnecessary_string_escapes: ignore
    unused_import: ignore

linter:
  rules:
    avoid_function_literals_in_foreach_calls: false
