// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ75dpEHZcLqbExYR2D34SE0a3POz7DfI',
    appId: '1:522401384798:android:ab9b08e2c9e057cf5a27cf',
    messagingSenderId: '522401384798',
    projectId: 'sparke-7lyyy6',
    storageBucket: 'sparke-7lyyy6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvUi2p_GNkvfnJya9rwuJ6ICAJpPZPidw',
    appId: '1:522401384798:ios:90dfb0c0e6c501a35a27cf',
    messagingSenderId: '522401384798',
    projectId: 'sparke-7lyyy6',
    storageBucket: 'sparke-7lyyy6.appspot.com',
    androidClientId: '522401384798-2scrprtmskurc8jqrj47qe7sf3r6hoqv.apps.googleusercontent.com',
    iosClientId: '522401384798-m1ivulmnm6jfpq9pknbse4o7a19r1d77.apps.googleusercontent.com',
    iosBundleId: 'com.failvc.sparke',
  );
}
